import { Geist, Geist_Mono } from "next/font/google";
import { FaFacebookF, FaTwitter, FaInstagram, FaLinkedin, FaYoutube} from "react-icons/fa";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <section className="w-full h-80 bg-white flex justify-center items-center">
          <div className="w-2/4 h-3/5 flex justify-center items-center rounded shadow-md">
            <div className="w-2/5 h-5/6 pl-2">
              <img className="w-full h-full rounded" src="/bookTable.jpg" alt="" />
            </div>
            <div className="w-3/5 h-5/6 flex flex-col gap-3 pl-5 py-1">
              <h1 className="text-3xl font-bold">Join Our Community</h1>
              <p>Sign up & get 10 % of your first books.</p>
              <div className="w-full">
                <input className="shadow-md w-3/5 p-1.5" type="email" name="" id="" placeholder="your email" />
                <button className="p-1.5 bg-green-700 text-white">Subscribe</button>
              </div>
              <div className="flex justify-between w-2/4">
                <span className="bg-green-700 p-1.5 rounded-full flex justify-center items-center"><FaFacebookF className="text-white"/></span>
                <span className="bg-green-700 p-1.5 rounded-full flex justify-center items-center"><FaTwitter className="text-white"/></span>
                <span className="bg-green-700 p-1.5 rounded-full flex justify-center items-center"><FaInstagram className="text-white"/></span>
                <span className="bg-green-700 p-1.5 rounded-full flex justify-center items-center"><FaLinkedin className="text-white"/></span>
                <span className="bg-green-700 p-1.5 rounded-full flex justify-center items-center"><FaYoutube className="text-white"/></span>
              </div>
            </div>
          </div>
        </section>
        <footer className="w-full h-60 bg-gray-700 flex items-end justify-center">
          <div className="w-4/5 h-4/5">
            <div className="w-full">
              <div>

              </div>
              <div>

              </div>
            </div>
            <div>
              <div>

              </div>
              <div>
                
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
